apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
stringData:
  secret: replace-me
---
apiVersion: v1
kind: Secret
metadata:
  name: unsplash-secret
type: Opaque
stringData:
  access_key: replace-me
