server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    resolver 127.0.0.11 valid=30s ipv6=off;

    set $auth_upstream auth-service:3001;
    set $reservation_upstream reservation-service:3002;
    set $external_upstream external-service:3003;
    set $order_upstream order-service:3004;
    set $notification_upstream notification-service:3005;
    set $product_upstream product-service:3006;
    set $payment_upstream payment-service:3007;

    # ВАЖНО: слэш в конце proxy_pass!
    location /api/auth/ {
        proxy_pass http://$auth_upstream/;
        proxy_set_header Host $host;
    }

    location /api/resource/ {
        proxy_pass http://$reservation_upstream/;
        proxy_set_header Host $host;
    }

    location /api/unsplash/ {
        proxy_pass http://$external_upstream/;
        proxy_set_header Host $host;
    }

    location /api/orders/ {
        proxy_pass http://$order_upstream/;
        proxy_set_header Host $host;
    }

    location /api/notifications/ {
        proxy_pass http://$notification_upstream/;
        proxy_set_header Host $host;
    }

    location /api/products/ {
        proxy_pass http://$product_upstream/;
        proxy_set_header Host $host;
    }

    location /api/payments/ {
        proxy_pass http://$payment_upstream/;
        proxy_set_header Host $host;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
